name: easy_permission_validator
description: An easy way to user PermissonHandler library.
version: 1.0.1
author: Ariel J. Martinez Viera <ariel.j.m.v@gmail.com>
homepage: https://github.com/ajviera/easy_permission_validator

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
